#!/usr/bin/env bash
# bash script that configure 'web-01' so that its firewall redirects,
# 'port 8080/TCP' to 'port 80/TCP'

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp