#!/usr/bin/env bash
# bash script that configures 'nginx' to run & listen to port 80
(sed -i 's/autoindex on/autoindex off/' /etc/nginx/sites-available/default && service nginx start && sleep 5 && service nginx stop) > /dev/null 2>&1
service nginx status | grep "not running"

