#!/usr/bin/env bash
# bash script that configures 'nginx' to run & listen to port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
